name: Feature Request
description: Suggest an idea or improvement for this profile
title: "[FEATURE] "
labels: ["enhancement"]
assignees:
  - duyet

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement! 💡

        Please fill out the information below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does this feature fall into?
      options:
        - Visual/Design improvement
        - New section or content
        - GitHub Actions workflow
        - Documentation
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples or Mockups
      description: If applicable, provide examples, links, or mockups
      placeholder: Links to examples, screenshots, or mockups...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
